_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
#  ROI_HEADS:
#    NUM_CLASSES: 6
  RESNETS:
    DEPTH: 50
    CHANNELS_PER_STAGE: [64, 128, 256, 256, 1024]

SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000

DATASETS:
  TRAIN: ("coco_2017_train_short",)
  TEST: ("coco_2017_val_short",)