_BASE_: "Base-Keypoint-RCNN-FPN.yaml"
SEED: 0
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 6
  WEIGHTS: "/home/ashkanaev/models/faster-rcnn-r-50-keys/output_keys_train_5/model_final_wo_solver_states.pth"
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
#    STRIDE_IN_1X1: False  # this is a C2 model
#    NUM_GROUPS: 32
#    WIDTH_PER_GROUP: 8
    DEPTH: 50
   # CHANNELS_PER_STAGE: [64, 128, 256, 256, 1024]
#  DEVICE: 'cpu'
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
#  STEPS: (210000, 250000)
  STEPS: (10000, 25000)
  WARMUP_ITERS: 10000
  MAX_ITER: 30000
#  MAX_ITER: 270000
  BASE_LR: 0.009
  IMS_PER_BATCH: 4
  CHECKPOINT_PERIOD: 500
DATASETS:
  TRAIN: ("keypoints_coco_2017_train_short",)
  TEST: ("keypoints_coco_2017_val_short",)

DATALOADER:
  NUM_WORKERS: 4

OUTPUT_DIR: './jobs/output_keys_test_new_keys_2'
